<?php

/**
 * @file
 * Contains important hooks.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Hide all none ui patterns layouts.
 *
 * Implements hook_plugin_filter_TYPE_alter().
 */
function wingsuit_companion_plugin_filter_layout_alter(array &$definitions, array $extra, $consumer) {
  /**
   * @var string $key
   * @var \Drupal\Core\Layout\LayoutDefinition $definition
   */
  foreach ($definitions as $key => $definition) {
    if ($definition->getProvider() !== 'wingsuit') {
      unset($definitions[$key]);
    }
    $additional = $definition->getAdditional();
    if ($definition->getProvider() === 'wingsuit' && isset($additional['visibility'] ) ) {
      $apps = array_map('trim', explode('|', $additional['visibility']));
      if (!in_array('drupal', $apps)) {
        unset($definitions[$key]);
      }
    }
  }

}

/**
 * Implements hook_help().
 */
function wingsuit_companion_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wingsuit_companion module.
    case 'help.page.wingsuit_companion':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module add Wingsuit Theme extensions.') . '</p>';
      return $output;

    default:
  }
}
